# Generated by Django 3.0.8 on 2020-07-23 13:37

import ckeditor.fields
import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quoraa', '0002_auto_20200723_1811'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question_data',
            name='datee',
            field=models.DateTimeField(default=datetime.datetime(2020, 7, 23, 19, 7, 4, 909691), verbose_name='Date Posted'),
        ),
        migrations.AlterField(
            model_name='question_data',
            name='questions',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
