# Generated by Django 3.0.8 on 2020-07-24 13:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quoraa', '0003_auto_20200723_1907'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='email',
            field=models.EmailField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='question_data',
            name='datee',
            field=models.DateTimeField(default=datetime.datetime(2020, 7, 24, 19, 17, 45, 491920), verbose_name='Date Posted'),
        ),
    ]
